name: Deploy Vue to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm install
        working-directory: P1

      - run: npm run build
        working-directory: P1

      - uses: actions/upload-pages-artifact@v3
        with:
          path: P1/dist

      - uses: actions/deploy-pages@v4

permissions:
  pages: write
  id-token: write
